### PR TITLE
Move op index & others

### PR DESCRIPTION
**Pull request by MarcelWiedenmann**
This PR comprises a set of rather loosely related changes. The main topics are:
-  More explicit decoupling of the individual parts of the matching infrastructure (Op discovery & indexing, Transformer indexing & matching)
- Treat former Op aliases as "proper" Op names
- Reduce dependencies on plugin/service infrastructure
- Disable prefix search. See #20.

Feel free to approve or reject these changes separately.

The PR does not yet deal with the removal of all parts of the plugin system. `OpService` and `TypeService` still exist and use other services internally. In particular, `OpService` still relies on `PluginService` to collect Ops and Transformers.

### CODE REVIEW

**Comment by MarcelWiedenmann** [comment]
The diffs of [DefaultOpTypeMatchingService](https://github.com/scijava/scijava-ops/pull/21/commits/a22af35c3afb1cc9d421e05279fd8e31585d96c5#diff-c9d1e6a95c7e5ad59d238d333dba4dfc) and [DefaultOpTransformerService](https://github.com/scijava/scijava-ops/pull/21/commits/51fda7440a0c656d84c87fd82594b5c6591f0f1f#diff-62c5ef9ef38410b69893c521fff95b4a) got polluted by formatting, sorry about that. I should be using the eclipse preferences from [imagej/imagej](https://github.com/imagej/imagej/tree/master/config), is this correct?

**Comment by ctrueden** [comment]
> I should be using the eclipse preferences from imagej/imagej - are those the right ones?

You and @gab1one should just _stop autoformatting on save_. It creates tons of problems. We can try to fix the autoformatters but it is low priority. If you want to format a code block that you just wrote, select it and then shift+ctrl+F it.

**Comment by MarcelWiedenmann** [comment]
Yes, I usually turn off save actions when working on already existing files and only use them for new files, forgot it here. I know about Shift+Ctrl+F, I mostly use save actions for clean-ups (making variables final etc.). It's a pity that there's no Shift+Ctrl+F equivalent for that.

**Comment by ctrueden** [comment]
> It's a pity that there's no Shift+Ctrl+F equivalent for that.

For Clean Up, I usually type (on macOS): <kbd>option</kbd>+<kbd>command</kbd>+<kbd>T</kbd> and then <kbd>C</kbd>,<kbd>C</kbd>,<kdb>return</kbd>. Yeah, no official shortcut, but it's still quite fast. Unfortunately, I believe Clean Up is always global to the file, rather than operating on the current selection, so it will not help you here. This is why you see me adding `final` keywords by hand sometimes.

**Comment by MarcelWiedenmann** [comment]
Cleaned up the diffs some more, the PR should be ready for review now.

**Comment by ctrueden** [comment]
Darn, I completely forgot about this PR, and since then work continued on the migrate-imagej-ops branch, with @gselzer redoing some of the work you had already done here.

I have now reconciled the branches, fixing conflicts, etc. Some of the work here might was lost: in particular, the separation of the op index into its own `OpIndex` class. But because the op index was still simplified to a map instead of a tree data structure, it is not so terrible leaving it in the `OpService` for now. We should still separate it at some point soon. Also, the goal of keeping the iteration order consistent and sorted is probably not met now—@gselzer just used a normal `HashMap` rather than anything fancy like `TreeMap` (always sorted) or `LinkedHashMap` (preserves insertion order).

Anyway, all commits compile with passing tests, and are still a step forward, so I'll merge it now.

**Pull request merged**
